apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: twitter-client-job-cron
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: API_KEY
              value: 
            - name: API_SECRET
              value: 
            - name: DB_PASS
              value: 
            - name: DB_HOST
              value: 
            - name: DB_PORT
              value: 
            name: twitter-client
            image: 172.30.1.1:5000/twitter-project/twitter-client
            command: ["python", "app.py"]
          restartPolicy: OnFailure